root: ./

​structure:  
    readme: README.md  
    summary: SUMMARY.md​
    
redirects:  
    docs/beta/experience-platform-extension: docs/release-notes
    docs/v/AEP-Edge-Docs/using-mobile-extensions/adobe-edge-consent: docs/consent-for-edge-network
